# Exploration: structure of simulation_results.parquet (Brandt panel review)
suppressMessages({library(arrow); library(dplyr)})
d <- read_parquet("data/processed/universal_sm_hybrid/simulation_results.parquet")
cat("rows:", nrow(d), "\n")
print(sapply(d, class))
cat("\nroute_chr values:\n"); print(table(d$route_chr, useNA = "ifany"))
cat("\nself_employed_flag:\n"); print(table(d$self_employed_flag, useNA = "ifany"))
cat("\neligible_flag:\n"); print(table(d$eligible_flag, useNA = "ifany"))
cat("\nany_retirement_access_v2_chr:\n"); print(table(d$any_retirement_access_v2_chr, useNA = "ifany"))
cat("\nWeighted universe (M):", sum(d$WPFINWGT)/1e6, "\n")
cat("Weighted eligible (M):", sum(d$WPFINWGT[d$eligible_flag])/1e6, "\n")
cat("\nmatch_rate_pp_num summary:\n"); print(summary(d$match_rate_pp_num))
cat("\ndefault_contrib_num summary:\n"); print(summary(d$default_contrib_num))
cat("\nmatch_per_worker_num summary:\n"); print(summary(d$match_per_worker_num))
cat("\nfiling groups:\n"); print(table(d$filing_group_chr, useNA="ifany"))
