# 00_inspect.R — schema and value inspection (run from repo root)
suppressPackageStartupMessages({library(arrow); library(dplyr)})

sim <- read_parquet("data/processed/universal_sm_hybrid/simulation_results.parquet")
cat("=== simulation_results columns ===\n")
print(names(sim))
cat("\nroute_chr values:\n"); print(table(sim$route_chr, useNA = "ifany"))
cat("\nany_retirement_access_v2_chr values:\n"); print(table(sim$any_retirement_access_v2_chr, useNA = "ifany"))
cat("\nhas_existing_dc_flag:\n"); print(table(sim$has_existing_dc_flag, useNA = "ifany"))
cat("\neligible_flag:\n"); print(table(sim$eligible_flag, useNA = "ifany"))
cat("\nweighted universe (M):", sum(sim$WPFINWGT)/1e6, "\n")
cat("weighted eligible (M):", sum(sim$WPFINWGT[sim$eligible_flag])/1e6, "\n")

mod <- read_parquet("data/processed/sipp_modeled.parquet")
cat("\n=== sipp_modeled columns ===\n")
print(names(mod))
cat("\nin_universe:\n"); print(table(mod$in_universe, useNA = "ifany"))
cat("weighted in-universe (M):", sum(mod$weight[mod$in_universe])/1e6, "\n")
cat("\nhas SSUID/PNUM?:", all(c("SSUID","PNUM") %in% names(mod)), "\n")
cat("\nsm_match_per_person summary (in universe):\n")
print(summary(mod$sm_match_per_person[mod$in_universe]))
cat("\nuniv_sm_match_m100 summary (in universe):\n")
print(summary(mod$univ_sm_match_m100[mod$in_universe]))
